import os
import markdown
from weasyprint import HTML, CSS

# 确保工件目录存在
ARTIFACT_DIR = "app/artifacts"
os.makedirs(ARTIFACT_DIR, exist_ok=True)

# 基础 CSS 样式：医疗报告风格，干净、专业
REPORT_CSS = """
@page {
    size: A4;
    margin: 2.5cm;
}
body {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #333;
}
h1 {
    color: #2c3e50;
    border-bottom: 2px solid #2c3e50;
    padding-bottom: 10px;
    margin-top: 0;
}
h2 {
    color: #2980b9;
    margin-top: 25px;
    border-bottom: 1px solid #eee;
    padding-bottom: 5px;
}
h3 {
    color: #34495e;
    font-size: 13pt;
    margin-top: 20px;
}
ul, ol {
    margin-bottom: 15px;
}
li {
    margin-bottom: 5px;
}
code {
    background-color: #f8f9fa;
    padding: 2px 4px;
    border-radius: 3px;
    font-family: Consolas, monospace;
    font-size: 0.9em;
}
pre {
    background-color: #f8f9fa;
    padding: 10px;
    border: 1px solid #e9ecef;
    border-radius: 5px;
    overflow-x: auto;
}
.footer {
    position: fixed;
    bottom: 0;
    right: 0;
    font-size: 9pt;
    color: #999;
}
"""

def save_markdown_as_pdf(task_id: str, markdown_text: str) -> str:
    """
    将 Markdown 转换为带样式的 PDF 报告
    """
    # 1. Markdown -> HTML
    # extensions: 'extra' 支持表格、脚注等；'nl2br' 将换行符转换为 <br>
    html_body = markdown.markdown(markdown_text, extensions=['extra', 'nl2br'])

    # 2. 包装完整的 HTML 结构
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Report {task_id}</title>
    </head>
    <body>
        {html_body}
        <div class="footer">Generated by Medical AI TechRadar | Task ID: {task_id}</div>
    </body>
    </html>
    """

    # 3. 生成 PDF
    pdf_path = os.path.join(ARTIFACT_DIR, f"{task_id}.pdf")
    
    # 使用 WeasyPrint 渲染
    HTML(string=full_html).write_pdf(
        pdf_path, 
        stylesheets=[CSS(string=REPORT_CSS)]
    )

    return pdf_path